name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Ruby
        uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Set credentials
        run: |
          mkdir -p $HOME/.gem
          cat > $HOME/.gem/credentials << EOF
          ---
          :rubygems_api_key: ${RUBYGEMS_API_KEY}
          EOF
          chmod 0600 $HOME/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

      - name: Build and publish gem
        run: |
          gem build *.gemspec
          gem push *.gem

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          gh release create ${TAG_NAME} \
            --title "${TAG_NAME}" \
            --notes "$(cat CHANGELOG.md | sed -n "/^## \\[${TAG_NAME#v}\\]/,/^## /p" | sed '$ d')" \
            *.gem
